[package]
name = "oro-classic-resolver"
version = "0.1.0"
authors = ["Kat Marchán <kzm@zkat.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
package-spec = { path = "../package-spec" }
rogga = { path = "../rogga" }
oro-node-semver = { path = "../oro-node-semver" }

thiserror = "1.0.20"
async-trait = "0.1.36"
